#! /usr/bin/env python3
# High-Level Gopher Client - Chapter 1 - gopherclient.py

import gopherlib, sys
host = sys.argv[1]
file_name = sys.argv[2]

f = gopherlib.send_selector(file_name,host)
for line in f.readlines():
    sys.stdout.write(line)
